sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alleshka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alleshka/docker-react npm run test

deploy: 
  provider: elasticbenstalk
  region: "us-east-2"
  app: "docker-application"
  env: "Dockerapplication-env"
  bucket_name: "elasticbeanstalk-us-east-2-529363392627"
  bucket_path: "docker-application"
  on: 
    branch: master